{
 "title": "Looseleaf",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "Logs", "query": "loki" },
   { "name": "instance", "query": { "query": "query_result(looseleaf_up{})" } }
  ]
 },
 "panels": [
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "looseleaf_http_request_time{job=~\"$instance\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(looseleaf_http_request_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(looseleaf_http_error_500_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "5xx"
    },
    {
     "expr": "rate(looseleaf_http_error_400_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(looseleaf_db_errors_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "db"
    }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Database Access Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "looseleaf_db_time{job=~\"$instance\"}",
     "legendFormat": "Access Time"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(looseleaf_db_reads_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(looseleaf_db_writes_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Writes"
    },
    {
     "expr": "rate(looseleaf_db_deletes_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Deletes"
    },
    {
     "expr": "rate(looseleaf_db_errors_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Database Keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "looseleaf_db_keys{job=~\"$instance\"}",
     "legendFormat": "Keys"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "looseleaf_db_size{job=~\"$instance\"}",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "LOGS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{level=\"INFO\"} | json",
     "maxLines": 20
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"} | json",
     "maxLines": 20
    }
   ]
  }
 ]
}