<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.io7m.primogenitor</groupId>
    <artifactId>com.io7m.primogenitor.lite</artifactId>
    <version>9.2.0</version>
  </parent>

  <groupId>com.io7m.looseleaf</groupId>
  <artifactId>com.io7m.looseleaf</artifactId>
  <version>4.0.1-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>com.io7m.looseleaf</name>
  <description>Minimalist transactional HTTP key/value store</description>
  <url>https://www.io7m.com/software/looseleaf/</url>

  <modules>
    <module>com.io7m.looseleaf.cmdline</module>
    <module>com.io7m.looseleaf.database.api</module>
    <module>com.io7m.looseleaf.database.sqlite</module>
    <module>com.io7m.looseleaf.documentation</module>
    <module>com.io7m.looseleaf.grafana</module>
    <module>com.io7m.looseleaf.oci</module>
    <module>com.io7m.looseleaf.protocol.v1</module>
    <module>com.io7m.looseleaf.security</module>
    <module>com.io7m.looseleaf.server.api</module>
    <module>com.io7m.looseleaf.server</module>
    <module>com.io7m.looseleaf.tests</module>
  </modules>

  <properties>
    <io7m.workID>15c3b056-f4d4-3047-b260-f7944ba48996</io7m.workID>

    <!-- io7m dependencies. -->
    <com.io7m.quarrel.version>1.8.0</com.io7m.quarrel.version>
    <com.io7m.xstructural.version>2.0.1</com.io7m.xstructural.version>
    <com.io7m.trasco.version>3.1.1</com.io7m.trasco.version>

    <!-- Configuration -->
    <io7m.api.previousVersion>4.0.0</io7m.api.previousVersion>
    <io7m.java.targetJavaVersion>21</io7m.java.targetJavaVersion>

    <!-- Third-party dependencies. -->
    <helidon.version>4.4.0</helidon.version>
    <jackson.version>3.1.1</jackson.version>
    <jetty.version>11.0.26</jetty.version>
    <org.junit.version>5.14.4</org.junit.version>
    <logback.version>1.5.32</logback.version>
    <opentelemetry.version>1.60.1</opentelemetry.version>
  </properties>

  <scm>
    <url>https://www.github.com/io7m-com/looseleaf</url>
    <connection>scm:git:https://www.github.com/io7m-com/looseleaf</connection>
    <developerConnection>scm:git:https://www.github.com/io7m-com/looseleaf</developerConnection>
  </scm>

  <issueManagement>
    <url>https://www.github.com/io7m-com/looseleaf/issues</url>
    <system>GitHub Issues</system>
  </issueManagement>

  <distributionManagement>
    <site>
      <id>io7m.com</id>
      <name>io7m.com</name>
      <url>https://www.io7m.com/software/looseleaf</url>
    </site>
    <snapshotRepository>
      <id>central</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.io7m.junreachable</groupId>
        <artifactId>com.io7m.junreachable.core</artifactId>
        <version>4.0.2</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jproperties</groupId>
        <artifactId>com.io7m.jproperties.core</artifactId>
        <version>4.0.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jdeferthrow</groupId>
        <artifactId>com.io7m.jdeferthrow.core</artifactId>
        <version>1.3.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jmulticlose</groupId>
        <artifactId>com.io7m.jmulticlose.core</artifactId>
        <version>1.1.3</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jxtrand</groupId>
        <artifactId>com.io7m.jxtrand.vanilla</artifactId>
        <version>2.1.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jaffirm</groupId>
        <artifactId>com.io7m.jaffirm.core</artifactId>
        <version>4.0.1</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jlexing</groupId>
        <artifactId>com.io7m.jlexing.core</artifactId>
        <version>3.2.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jeucreader</groupId>
        <artifactId>com.io7m.jeucreader.core</artifactId>
        <version>3.0.1</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.repetoir</groupId>
        <artifactId>com.io7m.repetoir.core</artifactId>
        <version>1.0.1</version>
      </dependency>

      <!-- DB -->
      <dependency>
        <groupId>org.xerial</groupId>
        <artifactId>sqlite-jdbc</artifactId>
        <version>3.51.3.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.trasco</groupId>
        <artifactId>com.io7m.trasco.api</artifactId>
        <version>${com.io7m.trasco.version}</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.trasco</groupId>
        <artifactId>com.io7m.trasco.vanilla</artifactId>
        <version>${com.io7m.trasco.version}</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.anethum</groupId>
        <artifactId>com.io7m.anethum.api</artifactId>
        <version>1.1.1</version>
      </dependency>

      <!-- HTTP -->
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-servlet</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-security</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-jmx</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-util</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-http</artifactId>
        <version>${jetty.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.toolchain</groupId>
        <artifactId>jetty-jakarta-servlet-api</artifactId>
        <version>5.0.2</version>
      </dependency>
      <dependency>
        <groupId>io.helidon</groupId>
        <artifactId>helidon-bom</artifactId>
        <type>pom</type>
        <version>${helidon.version}</version>
        <scope>import</scope>
      </dependency>

      <!-- JSON -->
      <dependency>
        <groupId>tools.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.io7m.dixmont</groupId>
        <artifactId>com.io7m.dixmont.core</artifactId>
        <version>3.1.0</version>
      </dependency>

      <!-- CLI -->
      <dependency>
        <groupId>com.io7m.quarrel</groupId>
        <artifactId>com.io7m.quarrel.core</artifactId>
        <version>${com.io7m.quarrel.version}</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.quarrel</groupId>
        <artifactId>com.io7m.quarrel.ext.logback</artifactId>
        <version>${com.io7m.quarrel.version}</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.quarrel</groupId>
        <artifactId>com.io7m.quarrel.ext.xstructural</artifactId>
        <version>${com.io7m.quarrel.version}</version>
      </dependency>

      <!-- Logging -->
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>${logback.version}</version>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-core</artifactId>
        <version>${logback.version}</version>
      </dependency>

      <!-- Build metadata. -->
      <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.annotation.bundle</artifactId>
        <version>2.0.0</version>
      </dependency>
      <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.annotation.versioning</artifactId>
        <version>1.1.2</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.primogenitor</groupId>
        <artifactId>com.io7m.primogenitor.support</artifactId>
        <version>9.2.0</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.jcip</groupId>
        <artifactId>com.io7m.jcip</artifactId>
        <version>2.0.1</version>
      </dependency>

      <!-- Test suite. -->
      <dependency>
        <groupId>nl.jqno.equalsverifier</groupId>
        <artifactId>equalsverifier</artifactId>
        <version>3.19.4</version>
      </dependency>
      <dependency>
        <groupId>net.jqwik</groupId>
        <artifactId>jqwik-api</artifactId>
        <version>1.9.3</version>
      </dependency>
      <dependency>
        <groupId>net.jqwik</groupId>
        <artifactId>jqwik-engine</artifactId>
        <version>1.9.3</version>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${org.junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>5.23.0</version>
      </dependency>

      <!-- OpenTelemetry -->
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>${opentelemetry.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-semconv</artifactId>
        <version>1.30.1-alpha</version>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-api-logs</artifactId>
        <version>1.26.0-alpha</version>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-sdk-logs</artifactId>
        <version>1.60.1</version>
      </dependency>
      <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>1.9.25</version>
      </dependency>
      <dependency>
        <groupId>com.squareup.okio</groupId>
        <artifactId>okio-jvm</artifactId>
        <version>3.16.4</version>
        <exclusions>
          <exclusion>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>*</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.io7m.stmp</groupId>
          <artifactId>string-template-maven-plugin</artifactId>
          <version>1.2.0</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>3.5.5</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>