FROM docker.io/library/alpine:${com.io7m.oci.versionAlpine}
FROM docker.io/library/eclipse-temurin:${com.io7m.oci.versionTemurin}

ENV PATH="/looseleaf/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/java/openjdk/bin"
ENV LOOSELEAF_HOME="/looseleaf"

COPY looseleaf /looseleaf

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="Minimalist transactional HTTP key/value store."
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m-com/looseleaf"
LABEL "org.opencontainers.image.title"="Looseleaf"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/looseleaf"
LABEL "org.opencontainers.image.version"="${project.version}"
LABEL "org.opencontainers.image.revision"="${buildNumber}"

ENTRYPOINT ["/looseleaf/bin/looseleaf"]
